wikimedia/wikipedia-preview

README.md, index.html, package-lock.json, package.json, scripts/demo.sh, webpack.config.js
https://phabricator.wikimedia.org/T255676
Once this PR is approved, I will merge it and rename the repo roughly at the same time, I will then go and fix CI.
=> Rename Previews to Preview (singular)

demo/articles/english.html, demo/articles/french.html, demo/articles/hindi.html, demo/articles/spanish.html, demo/articles/swahili.html, demo/index.html
as title
| Screenshot 1 | Screenshot 2 |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2560096/88536242-c4037500-d00b-11ea-9c40-b8fd92321785.png) | ![image](https://user-images.githubusercontent.com/2560096/88536247-c6fe6580-d00b-11ea-9493-20e8959aed32.png) |
=> Add view source link and update index path

.eslintrc.js, i18n/en.json, i18n/qqq.json, src/i18n.js, src/preview.js, test/i18n.test.js
Phabricator Ticket : https://phabricator.wikimedia.org/T250800
=> T250800 Setup Translatewiki

style/popup.less
Phabricator Link : https://phabricator.wikimedia.org/T256157
Landscape view, Portrait by default
_screenshot tested on chrome device simulator_
| Portrait | Landscape |
| --- | --- |
| ![localhost_8080_articles_english html(iPhone 6_7_8) (3)](https://user-images.githubusercontent.com/2560096/88713217-3911a000-d11b-11ea-8e5e-3401dec7268c.png) | ![localhost_8080_articles_english html(iPhone 6_7_8)](https://user-images.githubusercontent.com/2560096/88713221-3adb6380-d11b-11ea-820a-8ba31f89ecb7.png) |
| ![localhost_8080_articles_english html(iPhone 6_7_8) (4)](https://user-images.githubusercontent.com/2560096/88713213-38790980-d11b-11ea-91c8-4a6c739efb8f.png) | ![localhost_8080_articles_english html(iPhone 6_7_8) (1)](https://user-images.githubusercontent.com/2560096/88713220-3a42cd00-d11b-11e …
=> T256157 Landscape layout

demo/articles/hebrew.html
I think we miss this in hebrew article
=> Add missing material used sentence

style/popup.less
Phabricator Ticket : https://phabricator.wikimedia.org/T260153
| Tablet | Mobile |
| -- | -- |
| ![localhost_8080_articles_hindi html](https://user-images.githubusercontent.com/2560096/90139987-61370b00-dd79-11ea-99c1-eaa4ec6e3800.png) | ![localhost_8080_articles_hindi html(Surface Duo)](https://user-images.githubusercontent.com/2560096/90139991-6300ce80-dd79-11ea-987e-e22557434543.png) |
=> T260153 Add radius to touchable popup

style/popup.less
Reverts wikimedia/wikipedia-preview#44
=> Revert "T260153 Add radius to touchable popup"

src/event.js
https://phabricator.wikimedia.org/T259233#6463087
Follow up to #58, fixes two bugs found by @jpita
=> T259233: Wikipedia Preview dragging card gesture (follow up)

src/stories/preview.stories.js, style/preview.less
Fix the margin around the wordmark with and without thumbnail. Also add those cases to the Storybook.
=> Fix wordmark position in RTL and add to Storybook

style/gallery.less, style/preview.less
https://phabricator.wikimedia.org/T260407
Use system fonts according to the design style guide.
Also removed a bunch of `<something>:normal` useless CSS directives.
=> Use system font

style/link.css
slightly different but there is
| Before | After |
| --- | --- |
| ![localhost_8080_articles_arabic html(iPhone 6_7_8) (1)](https://user-images.githubusercontent.com/2560096/96096927-aa6a1f00-0ed0-11eb-8aa8-47cb2a34be36.png) | ![localhost_8080_articles_arabic html(iPhone 6_7_8)](https://user-images.githubusercontent.com/2560096/96096955-b1912d00-0ed0-11eb-8817-2d3fced69b0e.png) |
=> update link style in rtl direction

src/gallery/slider.js
=> avoid duplication of the image info in slider component

demo/css/article.css, demo/css/index.css, src/event.js, style/gallery.less, style/link.css, style/preview.less
Phabricator Ticket : https://phabricator.wikimedia.org/T260781
Problem
===
IE11 has a lot of styling issues
Solution
===
=> Fix IE11 styling

src/stories/gallery.stories.js
Phabricator Ticket : https://phabricator.wikimedia.org/T266675#6623145
(1)
(2)
=> T266675 fix gallery storybook and add error state

style/gallery.less
Small font size update. Let's wait for Sushanshu's go ahead before merging: https://phabricator.wikimedia.org/T267069#6631811
=> T267069 follow up: small font size update

src/stories/gallery.stories.js
Follow up ticket of https://github.com/wikimedia/wikipedia-preview/pull/89
=> T266675 : Follow up, fix the number of gallery items in Storybook

images/caption-cue-expanded.svg, src/gallery/slider.js, src/stories/gallery.stories.js, style/gallery.less
https://phabricator.wikimedia.org/T262371
Opting for leaving the caption div as `position: absolute` as it was already. As suspected the ellipsis seem to be more troublesome than what it's worth, want to explore alternatives with Sudhanshu. More thoughts inline
=> T262371: Fix multiline image caption

README.md, src/index.js, src/utils.js
Phabricator Ticket : https://phabricator.wikimedia.org/T278381
Debug Mode
=> T278381 Debug Mode

.eslintrc.js, package-lock.json, package.json, src/api.js, src/cachedRequest.js, src/event.js, src/gallery/fullscreen.js, src/gallery/slider.js, src/i18n.js, src/index.js, src/popup.js, src/preview.js, src/touchPopup.js, src/utils.js, test/.eslintrc.json, test/api.test.js
https://phabricator.wikimedia.org/T280061
Updates linter to 0.20. Please review and test carefully, more specific comments in-line. You should `rm -rf node_modules` and `npm install` first
=> T280061: Update eslint-config-wikimedia to 0.20

src/index.js
Phabricator Ticket : https://phabricator.wikimedia.org/T281299
The wikipedia preview doesn't work in image case
```html
<a href="https://en.wikipedia.org/wiki/Cat/">
</a>
```
=> T281299 Image Case

package-lock.json, package.json
=> Remove duplicate cypress in dependencies

cypress/integration/gallery-spec.js, cypress/integration/mobile-gallery-spec.js, cypress/integration/mobile-swipe-spec.js
Following Scrollable Test Cases for Mobile View (by swiping) have been added
1) Check the Scrollable of images within Gallery in Expanded Mode
2) Check the Scrollable of Caption in images of Gallery
=> Scrollable Test Cases for Mobile View Added

src/gallery/gestures.js, src/gallery/slider.js, style/gallery.less
Follow up to #116; addresses specific feedback from Sudhanshu: https://phabricator.wikimedia.org/T269787#7214284. The commit list includes all commits from original PR, but the 'Files changed' tab correctly shows only the new additions as the original PR has been already merged with `main`.
=> T269787: gallery zoom follow up

src/api.js, src/gallery/slider.js, src/stories/gallery.stories.js, src/utils.js, test/api.test.js, test/gallery.test.js
Phabricator Link: https://phabricator.wikimedia.org/T289273
Problem Statement
image doesn't showed up in some articles
Solution
use the proper imageinfo api
=> T289273 fix image not loading

src/gallery/gestures.js
https://phabricator.wikimedia.org/T289489
One class was missing for validation
=> T289489: Update isInvalidEvent

src/gallery/gestures.js
https://phabricator.wikimedia.org/T294959
=> T294959: fix TypeError bug

src/utils.js
Reverts wikimedia/wikipedia-preview#164
=> Revert "Include wpprov param to action API calls"

src/api.js
https://phabricator.wikimedia.org/T313596
=> Add analytics param to requestMwExtract()

demo/articles/english.html, src/index.js, src/utils.js, test/preview.test.js
https://phabricator.wikimedia.org/T317171
=> Add wprov to target href after popup is shown

style/link.css
I accidentally removed the cursor pointer when updating to the new style
=> Add cursor pointer style

style/gallery.less
https://phabricator.wikimedia.org/T352491
=> Set cursor pointer on gallery images

cypress/e2e/mobile-layout.cy.js, src/index.js, src/stories/preview.stories.js
Phabricator: https://phabricator.wikimedia.org/T293594
=> T293594 Show disambiguation extract in preview instead of custom disambiguation view

src/gallery/gestures.js, src/gallery/slider.js, style/gallery.less
https://phabricator.wikimedia.org/T287095
Demo: https://wikimedia.github.io/wikipedia-preview/T287095/articles/english.html
solution to prevent gallery slider glitch when user resize the window screen
=> T287095 add window resize handler for gallery component

src/components/preview.js, src/index.js, src/store.js, src/stories/preview.stories.js
add events and fix events handler and storybook
=> Reef - add events for try again button in error preview

style/popup.less
the background color is depends on the preview content (dark, light, detect)
=> remove unnecessary background from popup

src/components/galleryviewer.js, src/store.js, style/gallery.less
missing gesture touch events now, will do it in another pr
=> Update gallery caption style and action

README.md, src/index.js, src/utils.js
https://phabricator.wikimedia.org/T361703
Validate `popupContainer` and default it to `document.body` before trying to use it.
=> Validate and default popupContainer

cypress/e2e/mobile-swipe.cy.js, cypress/page-objects/preview-page.js, src/api.js, src/event.js, src/gallery/fullscreen.js, src/gallery/row.js, src/index.js, src/preview.js, src/stories/preview.stories.js, src/utils.js, style/gallery.less, style/preview.less, test/gallery.test.js, test/preview.test.js
https://phabricator.wikimedia.org/T360753
Demo: https://wikimedia.github.io/wikipedia-preview/T360753-gallery-images/articles/english.html
* Updates preview layout 
* Loading state will be maintained until both preview and media data are available
* Storybook and tests updated accordingly
---
=> T360753: Gallery row update

style/gallery.less
Phabricator: https://phabricator.wikimedia.org/T369097
Demo: https://wikimedia.github.io/wikipedia-preview/landscape-gallery-style/articles/english.html
=> T369097 gallery for landscape

package-lock.json
Phabricator: https://phabricator.wikimedia.org/T379710
make sure the dependencies up to date and all feature still the same
=> T379710 npm audit fix

package-lock.json, package.json
Phabricator: https://phabricator.wikimedia.org/T379710
=> Update version tag to 1.12.3

package-lock.json, package.json
there is a mistake setting storybook as the dependencies, moving to dev dependencies
Demo:
https://wikimedia.github.io/wikipedia-preview/storybook-dev-dependencies/
https://wikimedia.github.io/wikipedia-preview/storybook-dev-dependencies/storybook
=> Move storybook into dev dependencies

.github/workflows/main.yml
https://docs.github.com/en/actions/tutorials/authenticate-with-github_token#permissions-for-the-github_token
=> Grant the action the permissions for GitHub Pages Deploy Action
