wikimedia/wikipedia-preview

.circleci/config.yml, .gitignore, scripts/demo.sh
https://phabricator.wikimedia.org/T240012
When there's a new commit on the master branch, this CI configuration will generate the demo page and publish it to the gh-pages branch.
=> Publish compiled output to gh-pages

src/cachedRequest.js
the `cachedRequest` doesn't work in IE due to the missing support of `xhr.responseType = 'json'`, therefore use `xhr.responseText` to cover older version browser
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseText
Browser Compability of responseType
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType
=> T243774 use responseText instead response in xmlHttpRequest in IE

src/popup.js
Phabricator ticket : https://phabricator.wikimedia.org/T254212
Problem
===
The popup close immediately as soon as the mouse leaving the hover target element
Solution
===
FF doesn't have `event.toElement`, use `event.relatedTarget` instead
Note
===
it works on Firefox 77 / Firefox 58 (older)
=> T254212 Fix mouse leave event

style/link.css
Phab ticket: https://phabricator.wikimedia.org/T251265
This is a small follow up to #5 in order to [correctly centered](https://phabricator.wikimedia.org/T251265#6264751) the icon in the link CSS in Safari, this change works well with Firefox and Chrome also. 
Before | After 
--- | ---
---
https://stackoverflow.com/questions/17312521/vertical-align-is-not-working-in-safari-and-chrome
=> T251265: Fix icon centering

style/link.css
when working on demo site, I found the content with `line-height` has the styling issue, therefore adding it to match the content line-height
| Before | 
| --- | 
| <img width="658" alt="before-lineheight" src="https://user-images.githubusercontent.com/2560096/87725928-72165000-c7be-11ea-8814-5566d30ddbc5.png"> |
| After |
| --- |
| <img width="769" alt="after-lineheight" src="https://user-images.githubusercontent.com/2560096/87725925-717db980-c7be-11ea-91b1-68e2f4c89194.png"> |
=> add line-height to discovery link

src/event.js, src/index.js
PR related to https://github.com/wikimedia/wikipedia-preview/pull/20 
Comment related to https://github.com/wikimedia/wikipedia-preview/commit/beb4a3a7ca740947214c03e7ee11982697c775a1#commitcomment-40695177
Before we introducing the **delay feature for desktop**, we deal with all the events synchronously, **delay feature** brings the race condition and asynchronous event execution. Also note that there is only one instance of popup, unless we declare popup instance for each new popup event.
Therefore this let us think more about **the order of the event called**, and all of them should be **cleared empty once hide event is called**, this POC shows the following
1. A central place for all the event listener - No more manually remove each event listener, instead, remove ALL
1. A central …
=> stack timeout listener

src/index.js
Phab ticket: https://phabricator.wikimedia.org/T257645
For some reason [1] the `touchstart` event is not working as expected in Chrome, instead `touchend` does. I was able to replicate the same bug behavior description on Chrome in my desktop only (as in through dev tools mobile simulator), and not in Chrome on iphone. With `touchend` I get the expected behavior both on desktop and mobile with Chrome, Firefox and Safari. 
Leaving this TODO here though:
Note that the other `touchstart` event we have (to close popup) is working fine
---
[1]—
https://stackoverflow.com/questions/16703157/android-4-chrome-hit-testing-issue-on-touch-events-after-css-transform
https://benjaminhorn.io/code/touchstart-performance-issues-in-google-chrome/
https://stackoverflow.com/questions/38784878/touchstart-issue …
=> T257645: Switch from touchstart to touchend

src/event.js, src/index.js
Phab ticket: https://phabricator.wikimedia.org/T256213
What's needed:
> add a small delay to the closing of the popup when the mouse leaves the word
We tested a few delays with [this demo branch](https://github.com/wikimedia/wikipedia-preview/commit/0b6eaf28d8aeeb6a7b15c0630e7473597d71f8a6) and we're setting delay to 300ms based on that.
=> T256213: Add a small delay to onMouseLeave

src/index.js
It happens to my desktop touchable chrome browser and chrome mobile simulator 
Without this, it can open the gallery or Wikipedia page link accidentally when the popup open and the tap location is exactly the same place of the gallery or page link.
=> prevent any default behaviours when showing popup

src/index.js
https://phabricator.wikimedia.org/T258263
On mobile, the `touchstart`, `touchmove` and `touchend` events fire for every touch interactions (tap or scroll).
The `click` event represent a single tap and does not fire during a scroll gesture.
=> Use click to not interfere with scroll

package.json, src/popup.js
https://phabricator.wikimedia.org/T256724
In IE 11, the return value of `element.getBoundingClientRect()` doesn't contain `x` or `y` so the popup positioning was wrong (always below and to the right of the target element). This can cause the document width to change, a scrollbar to appear, and the text to reflow.
I think this was causing the issue described in the task but I can't be sure since I cannot reproduce it anymore.
Note: the change to the `dev` command in `package.json` is needed to allow a local connection to be established with crossbrowsertesting.com
=> IE: use bounding rectangle left/top instead of x/y

src/gallery.js, style/popup.less
https://phabricator.wikimedia.org/T256309#6392849
Small follow up for T256309 to fix gallery refresh button language, `lang` argument was missing in one `toggleLoading` call
=> T256309: Fix refresh button language

style/popup.less
Phabricator Ticket : https://phabricator.wikimedia.org/T260153
| Tablet | Mobile |
| -- | -- |
| ![localhost_8080_articles_hindi html](https://user-images.githubusercontent.com/2560096/90139987-61370b00-dd79-11ea-99c1-eaa4ec6e3800.png) | ![localhost_8080_articles_hindi html(Surface Duo)](https://user-images.githubusercontent.com/2560096/90139991-6300ce80-dd79-11ea-987e-e22557434543.png) |
interestingly, the recent change of the gallery markup (new container for the fullscreen gallery) fix the previous problem.
=> T260153 add border radius to touch popup

src/utils.js, test/utils.test.js
https://phabricator.wikimedia.org/T260436
This is a follow-up for #54, one more update to address [the remaining failing test](https://phabricator.wikimedia.org/T260436#6431566)
```
wikipedia-previews % npm test test/utils.test.js
> wikipedia-preview@1.0.3 test /Users/emedina/internet/wikimedia/wikipedia-previews
> mocha --require ignore-styles,@babel/register,jsdom-global/register "test/utils.test.js"
getWikipediaAttrFromUrl
✓ checks https://en.wikipedia.org/wiki/Cat
✓ checks https://en.m.wikipedia.org/wiki/Cat
✓ checks https://he.wikipedia.org/wiki/ירח
✓ checks https://he.wikipedia.org/wiki/ירח#Section
✓ checks https://ru.wikipedia.org/wiki/Каменобродский,_Альфред_Адольфович
✓ checks https://zh.wikipedia.org/wiki/太阳帆
✓ checks https://zh.wikipedia.org/w/index.php?title=太阳帆&action=purge
✓ …
```
=> T260436: improve detectLinks non-latin support 

src/event.js, src/preview.js, style/preview.less
https://phabricator.wikimedia.org/T259233
Currently, users need to tap 'Continue reading' button expand preview card. We would like to improve the user experience by allowing users to also be able to drag on mobile to interact with preview card
Allow users to drag up to expand preview card, drag down to close it, following specified requirements:
- To drag up and reveal more content, user should be able to drag up from either the body or header of the card
- To drag down and close the Wikipedia Preview card, users should only be able to drag down the card header. This is to not interfere with any possible text scrolling
- The tap gesture should remain unchanged
Solution inspired from #56 
---
=> T259233: Wikipedia Preview card dragging gestures

src/event.js, style/preview.less
Phabricator Ticket : https://phabricator.wikimedia.org/T257648
Problem: 
The preview popup may overflow behind the address bar when it expands.
Solution:
Fix the preview popup fix under the address bar when it exceeds the maximum height for the preview body
tested on
=> T257648 Desktop expand preview popup layout (max height calculation)

src/api.js, src/gallery/slider.js, src/utils.js, style/gallery.less, test/api.test.js, test/gallery.test.js, test/utils.test.js
https://phabricator.wikimedia.org/T261745
There are currently a few places where the gallery could be improved:
- it loads very big and heavy images for the fullscreen view
- it's missing the white background for transparent images
- has this issue: [T259854](https://phabricator.wikimedia.org/T259854)
- does not take advantage of the full screen for image layout
This ticket is aims to optimize the gallery with respect to some these. Specifically:
- use of `iiurlwidth` and `iiurlheight` props to make each fullscreen image as light as possible while still looking good (non-pixelated) on device
- see the table below for different size comparisons 
- include white background for transparent images
- resolves T259854
- use maximum screen size for image with the image info fixed on top with the …
=> T261745: gallery with best fit image

src/gallery/slider.js
Phabricator : https://phabricator.wikimedia.org/T262074
Problem
===
The gallery image has caption, description and also caption from the media list api.
Solution
===
The api doesn't return the caption, therefore first choose the media info description then media list caption.
=> Update order of the gallery image info caption or description

i18n/en.json, i18n/qqq.json, src/preview.js, style/preview.less
https://phabricator.wikimedia.org/T260364
> The file preview.js contains the rendering code for the 5 states of the preview: standard, loading, error, disambiguation, offline. They have almost identical chrome and layout but the markup and style are duplicated.
Refactoring with https://github.com/wikimedia/wikipedia-preview/commit/809c6d4f55eb6325e2ba6ab8437a67faf4f26281:
* Net difference in preview.js is even (_33 additions & 33 deletions_) but it should be easier to maintain this way
* Reduction of code lines come through preview.less. I opted to retain whatever specific CSS for each state as they were.
* The [storybook](https://github.com/storybookjs/storybook) was really useful to develop and test different states. Also tested on device.
=> T260364: Reduce code duplication for preview states

src/index.js
Phab ticket : https://phabricator.wikimedia.org/T263733
Problem 
===
Once hover action is called, the callback event will execute no matter which hovers user have
Solution
===
Remember the user hover id, and do the callback only the hover id and the current hover id is matched
Note
===
We don't clear the request event, that can be reserved as the cache for the next time the user hover it.
=> T263733 Shows the latest hover link (Race condition edge case)

src/gallery/slider.js
https://phabricator.wikimedia.org/T263009
When tapping the gallery next/previous buttons rapidly, sometimes the rendered image displays in a buggy in-transition state. The issue comes from a slight conflict between the touch events (`applyGestureEvent`) and the next/previous click events (`renderNext`): if a `touchstart` is triggered when the image is in-transition, the `temp.originalMarginLeft` value gets set to a in-transition value and therefore the image can "land" on the in-transition state.
Setting the final margin with `clientWidth` and `current` (like we do in `renderNext`) is more reliable because these won't reflect an in-transition state.
=> T263009: gallery sliding bug

.stylelintrc.json, browserslist, package-lock.json, package.json
Stylelint will output warnings for CSS features that may not fully work in our target browsers.
=> Make stylelint check for unsupported browser features

demo/articles/bahasaIndonesia.html, src/index.js
https://phabricator.wikimedia.org/T267069
The "Try again" offline preview CTA was not responding. This bug came from the preview refactor (#81): I forgot to update the selector in index.js. Note the `root` update in the Bahasa Indonesian article too.
=> T267069: Fix preview refresh bug

.stylelintrc.json
Some web features that we rely on are only partially supported by IE11. The warnings emitted by the plugin are coming from a good place but are not relevant in this case.
=> Allow features partially supported

src/gallery/slider.js
Phabricator : https://phabricator.wikimedia.org/T268057
Problem
===
The info icon is shown when the source link is not found from the api response
Solution
===
Simply hide the info element when there is no link given. However, it isn't idea when the page is **given offline then online** due to the reason how we design to refresh the image + info, therefore addition action during refresh image event.
=> T268057 hide info when it is not available and handle refresh event

images/caption-cue-expanded.svg, src/gallery/slider.js, style/gallery.less
https://phabricator.wikimedia.org/T262373
The gallery focus mode allows users to hide all other information in the gallery with a single tap to only display the image itself. 
Note this PR builds on top of https://github.com/wikimedia/wikipedia-preview/pull/85, hence the commit list showing all commits. The only commit relevant to focus mode at this point is https://github.com/wikimedia/wikipedia-preview/commit/26d274382c88b8ef88edacd9d706ae3a04180a40. 
Let's aim to merge #85 first.
=> T262373: add gallery focus mode

src/index.js
https://phabricator.wikimedia.org/T259490
When a target element already has an open popup attached to it, ignore subsequent hovers.
This is causing multiple hook onOpen events for the same popup in #94.
=> Ignore hover for link with open popup

src/event.js
https://phabricator.wikimedia.org/T276281
When preview popup expands down with limited screen space, it's expanding too far down the screen and overflows the available screen space. 
Let `setPreviewMaxHeight` also decide what's the most appropriate height when expanding down, similar to how we do it when expanding up.
=> T276281: Improve height setting when expanding down

README.md, src/index.js, src/utils.js, webpack.config.js
https://phabricator.wikimedia.org/T278377
Wikipedia Preview should print its version number to the javascript console, as that is useful information when a partner requests support.
=> T278377: Add version logging method

images/caption-cue.svg, style/gallery.less
https://phabricator.wikimedia.org/T269854
The gallery caption transition from expanded to collapsed is awkward because there's a `transition` rule for the caption text but not for the caption expand cue. 
I'm updating the collapsed state of the expand cue with an SVG (`svgo` ready) so that we can set a `transition` rule for the expand cue itself to go along with the caption text. This makes the overall animation smoother.
=> Smoothen gallery closing animation

demo/articles/english.html
Phabricator Ticket : https://phabricator.wikimedia.org/T281512
https://wikimedia.github.io/wikipedia-preview/demo/articles/english.html
as title, fix it
=> T281512 Wikipedia Preview english demo doesn't work in IE 11

src/gallery/event.js, src/gallery/fullscreen.js, src/gallery/slider.js
Phabricator Ticket : https://phabricator.wikimedia.org/T263598
=> T263598 keyboard shortcuts on gallery

src/index.js, test/api.test.js
Phabricator Ticket: https://phabricator.wikimedia.org/T282675
Solution : According to what I found on Popups extension, decode when we get the title.
=> T282675 URL encode issue on wp-preview

.storybook/main.js, src/stories/target.stories.js
Phabricator Ticket: https://phabricator.wikimedia.org/T282717
=> T282717 Add target stories for hyperlink, image and text

style/preview.less
https://phabricator.wikimedia.org/T285667 
We were missing styling support for unordered lists (aka bullet points).  Added padding so the bullet points line up with the paragraph above, as well as the same paragraph line height.
Before | After
------  | ------
=> T285667: Add styling for unordered lists 

style/gallery.less, style/popup.less
Phabricator Ticket: https://phabricator.wikimedia.org/T286654
the z-index 110 is too low, update it to 1100 to cover most of the cases, and update how bootstrap works for dark background screen.
[Bootstrap modal is 1050](https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss#L1036), so 1100 should be enough for us.
=> T286654 The Gallery / wp-dark-screen are hidden

src/event.js
The error state has no footer component. The code trying to set the preview max height breaks on it.
Assume a footer height of 0 when it is not there.
=> Handle no-footer case (error state)

src/index.js
https://phabricator.wikimedia.org/T288034
The `detectLinks` init option replaces the href attribute value with the standard no-op `javascript:;` in touch mode. It makes it impossible to use the standard right click options (like open in new tab) on devices that have both touch support and a pointer.
I removed the href replacement. I don't know why it was there. Please test carefully.
=> detectLinks: Leave href alone for right-click options

cypress/integration/gallery-spec.js, cypress/integration/mobile-gallery-spec.js
The above PR is created to remove a condition (res>1) that is preset in gallery-spec and mobile-gallery-spec. The condition checks the number of images to be above zero such that our test cases run. But now we have chosen words in the preview that always contain images. Thereby, I have removed the condition.
=> Removed a condition in Cypress Test Cases

src/index.js
The offline state doesn't have a footer with the "read on wiki" CTA. The code that tries to bind an even to that CTA crashes.
=> Handle the offline state having no cta footer

i18n/en.json, i18n/qqq.json, src/api.js, src/utils.js
The error state shouldn't happen too often but when it does, it's almost certainly caused by a configuration error. 
With this PR, editors and integrators get a little more information that they can try to understand or send us when they are stuck with unexpected error states.
=> Log errors to the console

src/utils.js
https://phabricator.wikimedia.org/T289500
Sometimes, the API returns the following HTML for the author of an image: `<div class=\"fn value\">\nUnknown artist<span style=\"display: none;\">Unknown artist</span>\n</div>`
The span is hidden so it's not really a problem but when we strip extract the text content from the HTML we get all text so we end up with "Unknown artistUnknown artist".
Added explicit removal of hidden spans from the strip function.
=> Remove invisible spans from HTML

src/gallery/slider.js
https://phabricator.wikimedia.org/T289471
Embedding the `<bdi>` within the existing `<div>` (instead of replacing the existing `<div>` with `<bdi>`) because in testing I’m seeing that replacing the `<div>` messes with the the text placement for the author.
=> T289471: Add bdi tags for gallery text

src/gallery/slider.js, style/gallery.less
https://phabricator.wikimedia.org/T289471
Follow up to #149, this include the ellipsis in context with `<bdi>` text
=> T289471: Include ellipsis in context with bdi text

src/utils.js
https://phabricator.wikimedia.org/T297172
This allows analytics to distinguish API requests coming from touch devices.
=> Use a distinct wprov param for touch devices

src/stories/preview.stories.js, style/preview.less
https://phabricator.wikimedia.org/T325556
Exact wordmark size (170px) needs to be validated by design before merging.
=> Wordmark size

README.md, demo/articles/english.html, demo/articles/spanish.html, src/index.js, src/preview.js, src/stories/preview.stories.js, style/preview.less
https://phabricator.wikimedia.org/T345056
Demo: https://wikimedia.github.io/wikipedia-preview/T345056-dark-mode/
This the first step for supporting dark mode in the Wordpress plugin: the dark mode feature will be native to the core library and the plugin requests it as necessary. I've made the spanish demo page an example with the dark view, for simplicity.
=> T345056: dark mode

src/index.js
https://phabricator.wikimedia.org/T345056
Another followup: when we update the color scheme on the fly (because of the wordpress plugin dark mode toggle, for example) we need the latest value to be propagated to `showPopup` in order for preview to render with current scheme after re-initializing
=> T345056: Fix closure issue

demo/css/link.css
Phabricator: https://phabricator.wikimedia.org/T360002
this is not being used, anyone can overwrite the styling of the link (including wordpress style)
=> T360002 remove font weight setting for link

src/components/preview.js, src/index.js, src/store.js, src/stories/preview.stories.js, src/stories/target.stories.js, style/popup.less, style/preview.less
As part of the Wikipedia Preview refactor (https://phabricator.wikimedia.org/T363468), this refactors the dark theme class names placement from `.wikipediapreview` to top level `.wp-popup-container`
=> Place dark theme class names higher up the DOM

demo/css/link.css
Phab ticket: https://phabricator.wikimedia.org/T363481
Demo: https://wikimedia.github.io/wikipedia-preview/T363481-underline/articles/english.html
Wikipedia Preview links styling is currently implemented using a pseudo element (`::after`). The following issues have been found to be likely due to this implementation:
* When the target is on more than one line, the underline disappears
* The gap between the word(s) and the underline is not part of the element so moving the mouse there will cause the popup to disappear
This PR uses `text-decoration` instead to fix issues above, sample below:
=> T363481: Use text-decoration for link style

cypress/e2e/active.cy.js, cypress/e2e/expand.cy.js, cypress/e2e/layout.cy.js, cypress/e2e/page-movement.cy.js, cypress/page-objects/preview-page.js, src/event.js, src/preview.js
https://phabricator.wikimedia.org/T363802
Close icon (x) is redundant on desktop since hovering out of the preview closes it. Therefore removing it.
=> Remove close icon on desktop

demo/css/link.css
https://phabricator.wikimedia.org/T363481
Follow up to  #199, removing text decoration color to cover dark mode support
=> T363481: Remove text decoration color

demo/articles/arabic.html, demo/articles/hindi.html, demo/articles/spanish.html, demo/articles/thai.html
for some reason, we didn't add detect links to some of the articles demo, we need it for the footer
=> add detectLinks true to init on demo page

style/gallery.less, style/preview.less
https://phabricator.wikimedia.org/T364881
* Favor `overflow: auto` over `overflow: scroll` since the former will only show scrollbars if they are needed
* Try to remove scrollbars with webkit and firefox specific attributes
=> Hide scrollbars

style/popup.less
https://phabricator.wikimedia.org/T360750#9856982
The arrow was 1rem (16px), the offset -8px and some clippath, which means that at some level it's height was <8px so a small gap appeared between it and the popup.
By setting it to 17px, we ensure rounding won't make it smaller than 8px.
Also, rem unit should be avoided for elements that are not expected to change with base text-size.
=> Make arrow a little bigger to avoid gap due to pixel rounding error

README.md
Phabricator: https://phabricator.wikimedia.org/T369118
=> T369118 docs: Update README to warn about Wikipedia Preview 1.9.0+ Unpkg issue
